# Generated by Django 4.1 on 2022-08-31 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("weight", models.FloatField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("Macho", "Male"),
                            ("Femea", "Female"),
                            ("Não Informado", "Undefined"),
                        ],
                        default="Não Informado",
                        max_length=15,
                    ),
                ),
                (
                    "groups",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="groups.groups",
                    ),
                ),
                (
                    "traits",
                    models.ManyToManyField(related_name="traits", to="traits.traits"),
                ),
            ],
        ),
    ]
