# Generated by Django 4.1 on 2022-08-31 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("traits", "0001_initial"),
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animals",
            name="groups",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="groups.groups",
            ),
        ),
        migrations.AlterField(
            model_name="animals",
            name="traits",
            field=models.ManyToManyField(related_name="animals", to="traits.traits"),
        ),
    ]
