# Generated by Django 4.1 on 2022-09-01 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("traits", "0001_initial"),
        ("animals", "0002_alter_animals_groups_alter_animals_traits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animals",
            name="groups",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="groups.groups",
            ),
        ),
        migrations.AlterField(
            model_name="animals",
            name="traits",
            field=models.ManyToManyField(related_name="traits", to="traits.traits"),
        ),
    ]
