# Generated by Django 4.1 on 2022-09-01 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("animals", "0003_alter_animals_groups_alter_animals_traits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animals",
            name="groups",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupsAnimals",
                to="groups.groups",
            ),
        ),
    ]
